### ISSUE TITLE
Crashes as soon as I schedule a request

### ISSUE THREAD

**Issue by SilverTab** [borchero/Squid#4] opened 2020-01-24 17:38 UTC
I'm using the sample code found in the "Basic" guide, however, as soon as I schedule the request, my app crashes in Concurrency.swift on line 60 with an EXC_BAD_INSTRUCTION:
 
![image](https://user-images.githubusercontent.com/15052/73090375-42892980-3ea6-11ea-91f4-4b05943393e2.png)

I can paste my code, but it's literally just the sample code found in the documentation, in a new (empty) project.

**Comment by borchero** [comment] 2020-01-24 18:27
I’ll have a look shortly!

**Comment by borchero** [comment] 2020-01-24 19:57
I'm sorry but I cannot reproduce this issue with the latest version of Xcode (11.3.1) and the latest tag (1.1.1). Try cleaning the build folder maybe? Otherwise I'll close the issue for now.

**Closed as completed** 2020-01-24 22:43 UTC

**Comment by SilverTab** [comment] 2020-01-26 13:35
That's so weird... just tried again in a new project, with 1.1.2, but no luck, can't schedule any request without crashing in that AtomicInt getter. I'm using Xcode 11.2.x, I'll try updating to the latest to see if it changes anything and report back...

**Comment by SilverTab** [comment] 2020-01-27 02:24
Update: No crash in Xcode 11.3.1! Weirdly enough though, it still consistently crashes in Xcode 11.2. No matter what I do!

**Comment by borchero** [comment] 2020-01-27 02:26
Great to hear ;) don't know about Xcode 11.2 though -- there were some bugs in the compiler for earlier versions of Xcode 11, maybe that's the cause (although improbable)
